"""Repository contracts for routines schedule and today use cases."""

from __future__ import annotations

from typing import Protocol

from app.models import CardLog, CardOverride, CardTemplate, RoutineAssignment, RoutineSchedule


class RoutineRepository(Protocol):
    def list_routines(self, *, status: str | None = None) -> list[RoutineSchedule]: ...
    def get_routine(self, routine_id: str) -> RoutineSchedule | None: ...
    def list_assignments(self, *, routine_id: str | None = None) -> list[RoutineAssignment]: ...
    def list_card_templates(self, *, status: str | None = None) -> list[CardTemplate]: ...
    def get_card_template(self, card_id: str) -> CardTemplate | None: ...
    def list_card_overrides_range(
        self,
        *,
        start_date: str,
        end_date: str,
    ) -> list[CardOverride]: ...
    def list_card_logs(self, *, date: str | None = None) -> list[CardLog]: ...
    def list_card_logs_range(self, *, start_date: str, end_date: str) -> list[CardLog]: ...
    def save_card_log(self, log: CardLog) -> None: ...
    def save_routine(self, routine: RoutineSchedule) -> None: ...
    def replace_assignments(
        self,
        *,
        routine_id: str,
        assignments: list[RoutineAssignment],
    ) -> None: ...
