/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description API root - health check.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Ingest
         * @description Re-ingest all FIT files into the database.
         */
        post: operations["trigger_ingest_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingest Status
         * @description Check whether new data needs ingesting.
         */
        get: operations["get_ingest_status_api_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Days
         * @description List available days of data.
         */
        get: operations["list_days_api_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/days/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Day
         * @description Get summary for a specific day (filesystem-based).
         */
        get: operations["get_day_api_days__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wellness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wellness
         * @description Get wellness data (HR, stress, SpO2, respiration, activity).
         */
        get: operations["get_wellness_api_wellness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sleep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sleep
         * @description Get sleep data (stages, assessment scores).
         */
        get: operations["get_sleep_api_sleep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hrv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hrv
         * @description Get HRV data (values, summaries).
         */
        get: operations["get_hrv_api_hrv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/daily-aggregates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Daily Agg
         * @description Get per-day aggregate stats for all metrics, plus period summary.
         */
        get: operations["get_daily_agg_api_daily_aggregates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skin-temp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Skin Temp
         * @description Get skin temperature data.
         */
        get: operations["get_skin_temp_api_skin_temp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sse Events
         * @description Server-Sent Events stream for real-time data updates.
         */
        get: operations["sse_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityReading */
        ActivityReading: {
            /** Timestamp */
            timestamp: string | null;
            /** Activity Type */
            activity_type: string;
            /** Intensity */
            intensity: number | null;
            /** Steps */
            steps: number | null;
            /** Calories */
            calories: number | null;
            /** Distance */
            distance: number | null;
        };
        /** BodyBatteryReading */
        BodyBatteryReading: {
            /** Timestamp */
            timestamp: string | null;
            /** Value */
            value: number;
        };
        /** DailyAggregatesResponse */
        DailyAggregatesResponse: {
            /** Days */
            days: string[];
            /** Daily */
            daily: components["schemas"]["DailyMetric"][];
            period: components["schemas"]["PeriodSummary"] | null;
        };
        /** DailyBodyBatteryStats */
        DailyBodyBatteryStats: {
            /** Avg */
            avg: number | null;
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /** Median */
            median: number | null;
            /** Q1 */
            q1: number | null;
            /** Q3 */
            q3: number | null;
        };
        /** DailyHeartRateStats */
        DailyHeartRateStats: {
            /** Avg */
            avg: number | null;
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /** Median */
            median: number | null;
            /** Q1 */
            q1: number | null;
            /** Q3 */
            q3: number | null;
            /** Resting */
            resting: number | null;
            /**
             * Zones
             * @default []
             */
            zones: components["schemas"]["HRZoneBucket"][];
        };
        /** DailyHrvStats */
        DailyHrvStats: {
            /** Weekly Avg */
            weekly_avg: number | null;
            /** Nightly Avg */
            nightly_avg: number | null;
            /** Status */
            status: string | null;
        };
        /** DailyMetric */
        DailyMetric: {
            /** Date */
            date: string;
            heart_rate: components["schemas"]["DailyHeartRateStats"];
            stress: components["schemas"]["DailyMetricStats"];
            body_battery: components["schemas"]["DailyBodyBatteryStats"];
            spo2: components["schemas"]["DailyMetricStats"];
            respiration: components["schemas"]["DailyMetricStats"];
            hrv: components["schemas"]["DailyHrvStats"];
            sleep: components["schemas"]["DailySleepStats"];
            skin_temp: components["schemas"]["DailySkinTempStats"];
        };
        /** DailyMetricStats */
        DailyMetricStats: {
            /** Avg */
            avg: number | null;
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
            /** Median */
            median: number | null;
            /** Q1 */
            q1: number | null;
            /** Q3 */
            q3: number | null;
        };
        /** DailySkinTempStats */
        DailySkinTempStats: {
            /** Deviation */
            deviation: number | null;
            /** Deviation 7 Day */
            deviation_7_day: number | null;
            /** Nightly Value */
            nightly_value: number | null;
        };
        /** DailySleepStats */
        DailySleepStats: {
            /** Score */
            score: number | null;
            /** Deep Score */
            deep_score: number | null;
            /** Rem Score */
            rem_score: number | null;
        };
        /** DaySummaryResponse */
        DaySummaryResponse: {
            /** Date */
            date: string;
            /** Total Files */
            total_files: number;
            /** File Types */
            file_types: {
                [key: string]: number;
            };
            /** Total Size Kb */
            total_size_kb: number;
        };
        /** DaysResponse */
        DaysResponse: {
            /** Days */
            days: string[];
            /** Total */
            total: number;
        };
        /** HRZoneBucket */
        HRZoneBucket: {
            /** Label */
            label: string;
            /** Min Bpm */
            min_bpm: number;
            /** Max Bpm */
            max_bpm: number | null;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeartRateReading */
        HeartRateReading: {
            /** Timestamp */
            timestamp: string | null;
            /** Value */
            value: number;
        };
        /** HrvResponse */
        HrvResponse: {
            /** Days */
            days: string[];
            /** Hrv Values */
            hrv_values: components["schemas"]["HrvValue"][];
            /** Hrv Summaries */
            hrv_summaries: components["schemas"]["HrvSummary"][];
        };
        /** HrvSummary */
        HrvSummary: {
            /** Date */
            date: string;
            /** Weekly Average */
            weekly_average: number | null;
            /** Last Night Average */
            last_night_average: number | null;
            /** Last Night 5 Min High */
            last_night_5_min_high: number | null;
            /** Baseline Low Upper */
            baseline_low_upper: number | null;
            /** Baseline Balanced Lower */
            baseline_balanced_lower: number | null;
            /** Baseline Balanced Upper */
            baseline_balanced_upper: number | null;
            /** Status */
            status: string;
        };
        /** HrvValue */
        HrvValue: {
            /** Date */
            date: string;
            /** Timestamp */
            timestamp: string | null;
            /** Value */
            value: number;
        };
        /** IngestResult */
        IngestResult: {
            /** Days Ingested */
            days_ingested: number;
            /** Duration Ms */
            duration_ms: number;
        };
        /** IngestStatus */
        IngestStatus: {
            /** Needs Ingest */
            needs_ingest: boolean;
            /** Last Ingest Time */
            last_ingest_time: string | null;
            /** Days In Db */
            days_in_db: number;
            /** Days On Disk */
            days_on_disk: number;
        };
        /** PeriodHeartRateStats */
        PeriodHeartRateStats: {
            /** Avg */
            avg: number | null;
            /** Avg Resting */
            avg_resting: number | null;
            /** Typical Low */
            typical_low: number | null;
            /** Typical High */
            typical_high: number | null;
            /**
             * Zones
             * @default []
             */
            zones: components["schemas"]["HRZoneBucket"][];
        };
        /** PeriodHrvStats */
        PeriodHrvStats: {
            /** Avg Nightly */
            avg_nightly: number | null;
            /** Avg Weekly */
            avg_weekly: number | null;
            /** Balanced Pct */
            balanced_pct: number | null;
            /**
             * Total Days
             * @default 0
             */
            total_days: number;
        };
        /** PeriodMetricStats */
        PeriodMetricStats: {
            /** Avg */
            avg: number | null;
            /** Typical Low */
            typical_low: number | null;
            /** Typical High */
            typical_high: number | null;
        };
        /** PeriodSkinTempStats */
        PeriodSkinTempStats: {
            /** Avg Deviation */
            avg_deviation: number | null;
            /** Max Deviation */
            max_deviation: number | null;
            /** Min Deviation */
            min_deviation: number | null;
            /** Avg Nightly */
            avg_nightly: number | null;
            /**
             * Days Tracked
             * @default 0
             */
            days_tracked: number;
        };
        /** PeriodSpo2Stats */
        PeriodSpo2Stats: {
            /** Avg */
            avg: number | null;
            /** Lowest Min */
            lowest_min: number | null;
            /**
             * Low Days
             * @default 0
             */
            low_days: number;
            /**
             * Total Days
             * @default 0
             */
            total_days: number;
        };
        /** PeriodSummary */
        PeriodSummary: {
            heart_rate: components["schemas"]["PeriodHeartRateStats"];
            stress: components["schemas"]["PeriodMetricStats"];
            respiration: components["schemas"]["PeriodMetricStats"];
            hrv: components["schemas"]["PeriodHrvStats"];
            spo2: components["schemas"]["PeriodSpo2Stats"];
            skin_temp: components["schemas"]["PeriodSkinTempStats"];
        };
        /** RespirationReading */
        RespirationReading: {
            /** Timestamp */
            timestamp: string | null;
            /** Value */
            value: number;
        };
        /** RestingHRReading */
        RestingHRReading: {
            /** Timestamp */
            timestamp: string | null;
            /** Resting Hr */
            resting_hr: number | null;
            /** Current Day Resting Hr */
            current_day_resting_hr: number | null;
        };
        /** SkinTempOvernight */
        SkinTempOvernight: {
            /** Date */
            date: string;
            /** Timestamp */
            timestamp: string | null;
            /** Local Timestamp */
            local_timestamp: number | null;
            /** Nightly Value */
            nightly_value: number | null;
            /** Average Deviation */
            average_deviation: number | null;
            /** Average 7 Day Deviation */
            average_7_day_deviation: number | null;
        };
        /** SkinTempResponse */
        SkinTempResponse: {
            /** Days */
            days: string[];
            /** Skin Temp Overnight */
            skin_temp_overnight: components["schemas"]["SkinTempOvernight"][];
        };
        /** SleepAssessment */
        SleepAssessment: {
            /** Date */
            date: string;
            /** Overall Score */
            overall_score: number | null;
            /** Deep Sleep Score */
            deep_sleep_score: number | null;
            /** Light Sleep Score */
            light_sleep_score: number | null;
            /** Rem Sleep Score */
            rem_sleep_score: number | null;
            /** Awake Time Score */
            awake_time_score: number | null;
            /** Awakenings Count */
            awakenings_count: number | null;
            /** Average Stress */
            average_stress: number | null;
        };
        /** SleepLevel */
        SleepLevel: {
            /** Date */
            date: string;
            /** Timestamp */
            timestamp: string | null;
            /** Level */
            level: string;
        };
        /** SleepResponse */
        SleepResponse: {
            /** Days */
            days: string[];
            /** Sleep Levels */
            sleep_levels: components["schemas"]["SleepLevel"][];
            /** Sleep Assessments */
            sleep_assessments: components["schemas"]["SleepAssessment"][];
        };
        /** SpO2Reading */
        SpO2Reading: {
            /** Timestamp */
            timestamp: string | null;
            /** Value */
            value: number;
            /** Confidence */
            confidence: number | null;
            /** Mode */
            mode: string;
        };
        /** StepsReading */
        StepsReading: {
            /** Timestamp */
            timestamp: string | null;
            /** Steps */
            steps: number;
            /** Distance */
            distance: number | null;
            /** Calories */
            calories: number | null;
        };
        /** StressReading */
        StressReading: {
            /** Timestamp */
            timestamp: string | null;
            /** Value */
            value: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WellnessResponse */
        WellnessResponse: {
            /** Days */
            days: string[];
            /** Heart Rate */
            heart_rate: components["schemas"]["HeartRateReading"][];
            /** Stress */
            stress: components["schemas"]["StressReading"][];
            /** Body Battery */
            body_battery: components["schemas"]["BodyBatteryReading"][];
            /** Spo2 */
            spo2: components["schemas"]["SpO2Reading"][];
            /** Respiration */
            respiration: components["schemas"]["RespirationReading"][];
            /** Activity */
            activity: components["schemas"]["ActivityReading"][];
            /** Steps Summary */
            steps_summary: components["schemas"]["StepsReading"][];
            /** Resting Hr */
            resting_hr: components["schemas"]["RestingHRReading"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_ingest_api_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
        };
    };
    get_ingest_status_api_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestStatus"];
                };
            };
        };
    };
    list_days_api_days_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaysResponse"];
                };
            };
        };
    };
    get_day_api_days__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wellness_api_wellness_get: {
        parameters: {
            query?: {
                /** @description Filter by date (YYYY-MM-DD) */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WellnessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sleep_api_sleep_get: {
        parameters: {
            query?: {
                /** @description Filter by date (YYYY-MM-DD) */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SleepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hrv_api_hrv_get: {
        parameters: {
            query?: {
                /** @description Filter by date (YYYY-MM-DD) */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HrvResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_daily_agg_api_daily_aggregates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyAggregatesResponse"];
                };
            };
        };
    };
    get_skin_temp_api_skin_temp_get: {
        parameters: {
            query?: {
                /** @description Filter by date (YYYY-MM-DD) */
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkinTempResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sse_events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
